version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: kanban-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/auth/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
      networks:
      - kanban-network

networks:
  kanban-network:
    driver: bridge
